### ISSUE TITLE
Include color bar for the IR satellite image

### ISSUE THREAD

**Issue by karstenpeters** [orcestra-campaign/weather#123]
It would be helpful if we had a colorer included in the GOES IR satellite images. Check if this is possible?!

**Comment by karstenpeters** [comment]
Hi, does anybody know which colormap is used to generate the IR satellite plot in goes.py and how to address it properly? @sortega87 @Lucalino ? I used 
`fig.colorbar(plot1),` 

with 
`plot1 = ax.imshow(
        goes_image.values,
        extent=extent,
        origin="upper",
    )`

I then got a colorbar, but that one does not really make sense (see attached)
![current_satellite_image_ir](https://github.com/user-attachments/assets/b3d487bf-ecea-433f-a9d2-99e4c623b121)

Thanks!

**Comment by HF7weatherman** [comment]
Hi @karstenpeters! I had a detailed look into this problem and it seems that we cannot provide a colorbar for this image. The data which is plotted is provided as RGB data, which is basically just color information as in a real photograph. This means that there is no unique mapping from a color to a value. This makes sense, for example you also cannot add a meaningful colormap to a picture of a landscape or a dog.
In particular, this means that the plot does not show brightness temperature, cloud top temperature or something else, but really is just an image on the IR channel. Because of that, I would leave it as is without a colorbar, and close the issue.

**Comment by HF7weatherman** [comment]
Since we did not find a way to plot the colorbar in multiple attempts, this issue will be closed now.
